import type { GlobalConfig } from 'payload'
import { isAuthenticated, readPublic } from '../../lib/access'
import { revalidateGlobalAfterChange } from '../../lib/revalidate'

export const ContactHero: GlobalConfig = {
  slug: 'contact-hero',
  label: 'Hero',
  admin: {
    group: 'Contact',
    description: 'Hero block on /contact: chapter eyebrow, two-line title, intro paragraph, hero image, and breadcrumb label. Edit the image and copy here; the address / hours / phone shown lower on the page live on Homepage → Settings.',
  },
  access: { read: readPublic, update: isAuthenticated },
  hooks: revalidateGlobalAfterChange(),
  fields: [
    { name: 'breadcrumbLabel', type: 'text', defaultValue: 'Plan Your Journey',
      admin: { description: 'Label for the current page in the breadcrumb (the "Home → <this>" trail).', hidden: true } },
    {
      name: 'title', type: 'group',
      admin: { description: 'Two-line hero title. Line A is roman; line B renders italic-friendly.' },
      fields: [
        { name: 'a', type: 'text', localized: true, defaultValue: 'Begin, when',
          admin: { description: 'First line of the hero title.' } },
        { name: 'b', type: 'text', localized: true, defaultValue: 'you are ready.',
          admin: { description: 'Second line of the hero title (italic-friendly).' } },
      ],
    },
    { name: 'lede', label: 'Intro paragraph', type: 'textarea', localized: true,
      defaultValue: 'Write to us in your own time, in your own words. A concierge will reply within twenty-four hours, in English or Bahasa Indonesia. There is no obligation — and no pressure — to proceed.',
      admin: { description: 'Intro paragraph beneath the title.', hidden: true } },
    { name: 'heroImage', type: 'upload', relationTo: 'media',
      admin: { description: 'Hero image displayed on the right of the title block. Recommended ~1600×1200, JPEG/WebP.' } },
    { name: 'imageHue', type: 'number', defaultValue: 3,
      admin: { description: 'Painted-SVG fallback hue when no image is uploaded (0–6, brand palette). 3 = deep accent.' } },
    { name: 'imageLabel', type: 'text', localized: true, defaultValue: 'PLAN YOUR JOURNEY',
      admin: { description: 'Caption label shown over the painted-SVG fallback if no hero image is uploaded.' } },
    { name: 'chapter', type: 'text', localized: true, defaultValue: 'Chapter VIII — Plan Your Journey',
      admin: { description: 'Small caps eyebrow above the hero title, e.g. "Chapter VIII — Plan Your Journey".', hidden: true } },
    // ── Visit section (merged from former ContactVisitSection global) ──────
    {
      name: 'visitSection',
      type: 'group',
      admin: { description: 'Lower "Find us in Nusa Dua" section on /contact. Address / hours values come from Settings — only the copy labels live here.' },
      fields: [
        { name: 'eyebrow', label: 'Label above heading', type: 'text', localized: true, defaultValue: 'Visit',
          admin: { description: 'Small-caps eyebrow above the heading.', hidden: true } },
        { name: 'headingPre', type: 'text', localized: true, defaultValue: 'Find us in',
          admin: { description: 'First part of the section heading (roman).' } },
        { name: 'headingItalic', type: 'text', localized: true, defaultValue: 'Nusa Dua.',
          admin: { description: 'Second part of the heading rendered in italic serif.' } },
        { name: 'body', type: 'textarea', localized: true,
          defaultValue: 'Within the BIMC Hospital Nusa Dua, on the southernmost reach of Bali. Twelve minutes from Ngurah Rai International Airport.',
          admin: { description: 'Body paragraph above the address block.', hidden: true } },
        { name: 'mapImage', type: 'upload', relationTo: 'media',
          admin: { description: 'Photo / map shown on the right side of the Visit section. Recommended ~1600×1200, 4:3 aspect.' } },
        { name: 'mapImageLabel', type: 'text', localized: true, defaultValue: 'NUSA DUA · BALI',
          admin: { description: 'Caption label shown over the painted-SVG fallback if no map image is uploaded.', hidden: true } },
        { name: 'mapImageHue', type: 'number', defaultValue: 4,
          admin: { description: 'Painted-SVG fallback hue when no map image is uploaded (0–6, brand palette).', hidden: true } },
        { name: 'openInMapsLabel', type: 'text', localized: true, defaultValue: 'Open in Maps',
          admin: { description: 'Text on the first ghost-style CTA below the address.', hidden: true } },
        { name: 'getDirectionsLabel', type: 'text', localized: true, defaultValue: 'Get directions',
          admin: { description: 'Text on the second ghost-style CTA.', hidden: true } },
        { name: 'clinicHoursLabel', type: 'text', localized: true, defaultValue: 'Hours · Clinic',
          admin: { description: 'Mono caption above the clinic-hours row.', hidden: true } },
        { name: 'conciergeHoursLabel', type: 'text', localized: true, defaultValue: 'Hours · Concierge',
          admin: { description: 'Mono caption above the concierge-hours row.', hidden: true } },
        { name: 'conciergeHoursValue', type: 'textarea', localized: true,
          defaultValue: 'Twenty-four hours\nReplies within ten minutes',
          admin: { description: 'Concierge-hours value (use a blank line to break onto a new line).' } },
      ],
    },
  ],
}
