import type { CollectionConfig } from 'payload'
import { isAuthenticated, readPublic } from '../lib/access'
import { revalidationHooks } from '../lib/revalidate'
import { seoGroup } from '../lib/seo'

export const ClinicCatalogueItems: CollectionConfig = {
  slug: 'clinic-catalogue-items',
  labels: { singular: 'Clinic Catalogue Item', plural: 'Clinic Catalogue Items' },
  admin: {
    useAsTitle: 'name',
    defaultColumns: [
      'name',
      'catalogueGroup',
      'mainCategory',
      'subCategory',
      'audienceTier',
      'sortOrder',
    ],
    group: 'Pricing',
    description:
      'The flat clinic price catalogue rendered as "The full clinic catalogue." on /pricing. Grouped by catalogueGroup → mainCategory. Editors edit a row here to update the price on the public site. Shares its full editorial field set with Procedures (description / detail / images / SEO) so every atom is preserved and CRUD-able; well-being-style relations (parentSubCategory) are intentionally absent — those items live in the Procedures collection under b. Treatments.',
  },
  access: {
    read: readPublic,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  hooks: {
    ...revalidationHooks(),
  },
  fields: [
    { name: 'slug', type: 'text', required: true, unique: true, index: true,
      admin: { description: 'URL fragment / catalogue key for this item.' } },
    { name: 'name', type: 'text', required: true,
      admin: { description: 'Display name shown on the /pricing catalogue row.' } },
    { name: 'shortName', type: 'text',
      admin: { description: 'Optional shorter label.' } },
    {
      name: 'catalogueGroup',
      type: 'select',
      required: true,
      options: [
        { label: 'Surgical', value: 'surgical' },
        { label: 'Machine', value: 'machine' },
        { label: 'Injection', value: 'injection' },
        { label: 'BTL (Hair Removal)', value: 'btl' },
      ],
      admin: { description: 'Which /pricing catalogue sheet this row belongs to.' },
    },
    { name: 'mainCategory', type: 'text',
      admin: { description: 'Main category — e.g. "Face & Neck", "Laser AFT Rejuvenation", "Dermal Fillers", "Upper Body".' } },
    { name: 'subCategory', type: 'text',
      admin: { description: 'Optional 3rd-level grouping label inside Main Category.' } },
    { name: 'unit', type: 'text',
      admin: { description: 'e.g. "1 ml", "per unit", "per thread", "Face", "Half Arm".' } },
    {
      name: 'audienceTier',
      type: 'select',
      defaultValue: 'standard',
      options: [
        { label: 'Standard', value: 'standard' },
        { label: 'BIMC Tourist', value: 'tourist' },
        { label: 'BIMC Kitas + KTP', value: 'kitas_ktp' },
        { label: 'Package', value: 'package' },
      ],
      admin: { description: 'Pricing tier for multi-tier rows (machine 3-tier).' },
    },
    { name: 'brand', type: 'text', admin: { description: 'Injection only — e.g. "Juvederm".' } },
    { name: 'productLine', type: 'text', admin: { description: 'Injection only — e.g. "Volux".' } },
    { name: 'manufacturer', type: 'text', admin: { description: 'Injection only — e.g. "Allergan".' } },
    { name: 'fdaApproved', type: 'checkbox', defaultValue: false,
      admin: { description: 'Injection only — FDA-approved badge.' } },
    {
      name: 'bodyZone',
      type: 'select',
      options: [
        { label: 'Face', value: 'face' },
        { label: 'Upper Body', value: 'upper-body' },
        { label: 'Lower Body', value: 'lower-body' },
        { label: 'Package', value: 'package' },
        { label: 'Other BTL', value: 'other' },
      ],
      admin: { description: 'BTL only — body zone for hair removal grouping.' },
    },
    { name: 'parentDiscipline', type: 'relationship', relationTo: 'disciplines',
      admin: { description: 'Optional — only used for recovery/wellness items that link to a discipline (e.g. recovery villas under Weight Loss).' } },
    { name: 'description', type: 'richText',
      admin: { description: 'Optional rich-text description (preserved for items that carry editorial copy alongside their catalogue price).' } },
    {
      name: 'sections',
      type: 'array',
      admin: { description: 'Optional body sections (preserved from Procedures schema for atom-completeness).' },
      fields: [
        { name: 'anchorId', type: 'text', required: true },
        { name: 't', type: 'text', required: true },
        { name: 'body', type: 'richText', required: true },
      ],
    },
    {
      name: 'faqs',
      type: 'array',
      admin: { description: 'Optional FAQ items (preserved from Procedures schema for atom-completeness).' },
      fields: [
        { name: 'q', type: 'text', required: true },
        { name: 'a', type: 'textarea', required: true },
      ],
    },
    { name: 'heroImage', type: 'upload', relationTo: 'media',
      admin: { description: 'Optional hero image.' } },
    {
      name: 'pricing',
      type: 'group',
      admin: { description: 'Catalogue pricing — drives the displayed price on /pricing.' },
      fields: [
        { name: 'priceIdr2025', type: 'number',
          admin: { description: 'Price in IDR (2025). AUD is derived from Settings.audToIdrRate at render-time — do not store AUD separately.' } },
        { name: 'priceIdr2026', type: 'number',
          admin: { description: 'Price in IDR (2026). AUD is derived from Settings.audToIdrRate at render-time — do not store AUD separately.' } },
        { name: 'priceIdrRangeLow', type: 'number', admin: { description: 'For range values.' } },
        { name: 'priceIdrRangeHigh', type: 'number' },
        { name: 'priceNotes', type: 'text', admin: { description: 'e.g. "Local Anesthesia", "General Anesthesia".' } },
        { name: 'displayYear', type: 'select', defaultValue: '2026',
          options: [{ label: '2025', value: '2025' }, { label: '2026', value: '2026' }],
          admin: { description: 'Which year to display by default.' } },
      ],
    },
    { name: 'featuredRank', type: 'number',
      admin: { description: 'Top-3 indicator (1, 2, or 3 — blank for non-featured).' } },
    { name: 'includesImplant', type: 'checkbox', defaultValue: false,
      admin: { description: 'Flagged from "*" marker in pricelist.' } },
    {
      name: 'detail',
      type: 'group',
      admin: { description: 'Optional detail fields (preserved for items that carry editorial copy alongside their catalogue price).' },
      fields: [
        { name: 'duration', type: 'text' },
        { name: 'recovery', type: 'text' },
        { name: 'included', type: 'array',
          fields: [{ name: 'value', type: 'text', required: true }] },
      ],
    },
    seoGroup,
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort within Main Category',
      defaultValue: 0,
      admin: {
        position: 'sidebar',
        description:
          'Order within mainCategory inside catalogueGroup. Lower numbers appear EARLIER. Use 10/20/30… leaving gaps for inserts.',
      },
    },
  ],
}
