import type { CollectionConfig } from 'payload'
import { isAuthenticated, readPublic } from '../lib/access'
import { revalidationHooks } from '../lib/revalidate'
import { seoGroup, sortOrderField } from '../lib/seo'
import { apiWarningField } from '../lib/api-warning'

export const Surgeons: CollectionConfig = {
  slug: 'surgeons',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'group', 'lead', 'sortOrder'],
    group: 'c. Doctors',
    description: 'The clinic\'s surgeons. Each record renders on: (1) the /surgeons listing card, (2) the /surgeons/{slug} detail page, (3) the Doctors mega-menu, (4) blog bylines when the surgeon is the author, (5) discipline + sub-category pages as Lead Surgeon. Edit ONCE here — every page using this doctor updates.',
  },
  access: {
    read: readPublic,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  hooks: revalidationHooks(),
  fields: [
    apiWarningField,
    { name: 'slug', type: 'text', required: true, unique: true, index: true,
      admin: { description: 'URL fragment for the doctor\'s page. "suka" → https://cosmedic.gaiada.online/surgeons/suka. Lowercase, hyphens only.' } },
    { name: 'name', type: 'text', required: true,
      admin: { description: 'Full formal name including credentials. Rendered as the page heading on /surgeons/{slug} and the byline on cards. e.g. "dr. I Made Suka Adnyana, SpBP-RE (K)".' } },
    { name: 'commonName', type: 'text',
      admin: { description: 'Short/familiar first name used in the mega-menu and breadcrumbs. e.g. "Suka".' } },
    { name: 'title', type: 'text', defaultValue: 'dr.',
      admin: { description: 'Honorific prefix shown before the name. Default "dr.".' } },
    { name: 'suffix', type: 'text',
      admin: { description: 'Post-nominals shown after the name on the bio page. e.g. "SpBP-RE (K)".' } },
    { name: 'spec', type: 'text',
      admin: { description: 'One-line specialty headline shown on the surgeon\'s grid card and as the eyebrow on /surgeons/{slug}. e.g. "Facial Aesthetics".' } },
    { name: 'train', type: 'text',
      admin: { description: 'Training narrative shown in the surgeon\'s bio sidebar. e.g. "Indonesia · Japan".' } },
    { name: 'proc', type: 'text',
      admin: { description: 'Memberships line shown as the "Distinction" stat block on /surgeons/{slug}. e.g. "ISAPS Member".' } },
    { name: 'credLine', type: 'text',
      admin: { description: 'Compact credentials line displayed under the name on the surgeon\'s grid card and bio aside. e.g. "ISAPS Member · 22 years experience".' } },
    { name: 'yearsInPractice', type: 'number',
      admin: { description: 'Big number shown in the "Years in practice" stat block on /surgeons/{slug}.' } },
    { name: 'hue', type: 'number', min: 0, max: 5, defaultValue: 0,
      admin: { description: 'Brand-palette colour token (0-5) used as the placeholder gradient when the portrait fails to load.' } },
    { name: 'group', type: 'select', required: true, defaultValue: 'plastic-surgery',
      admin: { description: 'Determines which column of the Doctors mega-menu this surgeon appears in: "Plastic Surgery" or "Aesthetic Medicine".' },
      options: [
        { label: 'Plastic Surgery', value: 'plastic-surgery' },
        { label: 'Aesthetic Medicine', value: 'aesthetic-medicine' },
      ] },
    { name: 'lead', type: 'checkbox', defaultValue: false,
      admin: { description: 'Featured-lead-surgeon flag. When TRUE, this surgeon gets the prominent feature panel on /surgeons and may appear on the homepage Surgeons section.' } },
    { name: 'bio', type: 'richText',
      admin: { description: 'Long-form biography rendered as the body content on /surgeons/{slug}. Rich text (headings, paragraphs, emphasis).' } },
    { name: 'specAreas', type: 'array',
      admin: { description: 'Chip-style specialty tags shown under the bio (and as the "Specialty" stat block). Add 3–5 short tags.' },
      fields: [{ name: 'value', type: 'text', required: true }] },
    { name: 'portrait', type: 'upload', relationTo: 'media',
      admin: { description: 'The surgeon\'s portrait shown on: (1) /surgeons grid card, (2) /surgeons/{slug} hero, (3) Doctors mega-menu thumbnail, (4) blog byline when this surgeon authored. Square crop ideal, ~500×500 minimum.' } },
    { name: 'portraitPosition', type: 'text', defaultValue: 'center 30%',
      admin: { description: 'CSS object-position value (e.g. "center 30%") to fine-tune the crop focal point of the portrait image.' } },
    {
      name: 'availabilitySchedule',
      type: 'array',
      admin: { description: 'Renders as the "Availability" line in the bio sidebar of /surgeons/{slug}. Each row = one weekday + time window. Sourced from clinic pricelist Further Info.' },
      fields: [
        { name: 'day', type: 'select', required: true,
          admin: { description: 'Weekday this row applies to.' },
          options: ['mon','tue','wed','thu','fri','sat','sun'].map(d => ({ label: d.toUpperCase(), value: d })) },
        { name: 'windowStart', type: 'text',
          admin: { description: 'Start of the consultation window, e.g. "09:00".' } },
        { name: 'windowEnd', type: 'text',
          admin: { description: 'End of the consultation window, e.g. "17:00".' } },
        { name: 'byAppointment', type: 'checkbox', defaultValue: true,
          admin: { description: 'When TRUE, the row is labelled "by appointment" (rather than walk-in).' } },
      ],
    },
    { name: 'languages', type: 'array',
      admin: { description: 'Languages this doctor consults in. Rendered as a row in the bio sidebar of /surgeons/{slug}.' },
      fields: [{ name: 'code', type: 'select', options: ['en','id','ja','fr','de'].map(c => ({ label: c, value: c })) }] },
    { name: 'credentialedProcedures', type: 'relationship', relationTo: 'procedures', hasMany: true,
      admin: { description: 'Procedures this surgeon is credentialed for. Drives the reverse-link "Performed by" lists on procedure detail / sub-category pages.' } },
    seoGroup,
    sortOrderField,
  ],
}
