import type { GlobalConfig } from 'payload'
import { isAuthenticated, readPublic } from '../lib/access'
import { revalidateGlobalAfterChange } from '../lib/revalidate'

export const Settings: GlobalConfig = {
  slug: 'settings',
  label: 'Settings',
  admin: {
    group: 'Homepage',
    description: 'Site-wide identity used on every page: name, address, contact details, WhatsApp number, currency rules, social links. Anything that appears in the footer, the contact page, or feeds the floating chrome.',
  },
  access: { read: readPublic, update: isAuthenticated },
  hooks: revalidateGlobalAfterChange(),
  fields: [
    { name: 'siteName', label: 'Site Name', type: 'text', defaultValue: 'BIMC CosMedic',
      admin: { description: 'Used in <title> tags, OG meta, footer copyright, header logo alt-text. Visible on every page.' } },
    { name: 'siteTagline', type: 'text', localized: true,
      admin: { description: 'Short tagline used in SEO meta + share previews. Not currently rendered on-screen.', hidden: true } },
    { name: 'audToIdrRate', label: 'AUD → IDR Rate', type: 'number', defaultValue: 12800,
      admin: { description: 'AUD → IDR conversion rate. Editing this re-pegs every AUD figure across the entire site. Auto-updated daily (±5% threshold). Use the "Fetch live rate" button below to check + apply the current rate on demand.' } },
    {
      type: 'ui',
      name: 'liveRateWidget',
      admin: { components: { Field: '@/components/LiveRateButton' } },
    },
    { name: 'rateLockedManually', label: 'Lock Rate Manually', type: 'checkbox', defaultValue: false,
      admin: { description: 'When checked, the daily auto-fetch will not overwrite the rate above. Uncheck to resume auto-updates.' } },
    { name: 'rateLastFetchedAt', type: 'text',
      admin: { description: 'Set automatically. Timestamp of the last rate check (auto or manual).', readOnly: true } },
    { name: 'rateSource', type: 'text',
      admin: { description: 'Set automatically. Source and timestamp of the last fetch.', readOnly: true } },
    { name: 'roundIdrTo', label: 'Round IDR To', type: 'number', defaultValue: 50000,
      admin: { description: 'Round computed IDR to nearest N when converting from AUD. Default 50,000.' } },
    { name: 'contactEmail', label: 'General Email', type: 'text', defaultValue: 'cosmedic@bimcbali.com',
      admin: { description: 'General clinic email. Shown on /contact under "Direct lines · Email" AND in the footer "Connect" column.' } },
    { name: 'clinicEnquiryEmail', type: 'text',
      admin: { description: 'Inbox that receives enquiry-form submissions (the clinic-notify email fired on every new Enquiries record). Edit here to redirect enquiries without dev intervention. Falls back to MAIL_CLINIC_TO env, then to cosmedic@bimcbali.com.', hidden: true } },
    { name: 'pressEmail', type: 'text', defaultValue: 'press@bimccosmedic.com',
      admin: { description: 'Press / media email. Shown on /contact under "Direct lines · Press". Edit once here.', hidden: true } },
    { name: 'contactPhone', label: 'Concierge Phone', type: 'text',
      admin: { description: 'Concierge phone (E.164 formatted). Shown on /contact under "Direct lines · Concierge".' } },
    { name: 'whatsappNumber', label: 'WhatsApp Number', type: 'text', defaultValue: '+62-XXX-XXXX-XXXX',
      admin: { description: 'Concierge WhatsApp number. Single source for: the floating green WhatsApp bubble on every page (wa.me link built from the digits), the footer "Connect" column WhatsApp link, AND the /contact "Direct lines · WhatsApp" displayed value. Format: E.164 (+countrycode-number) — the digits are extracted for wa.me; the formatted string is what readers see.' } },
    { name: 'addressLine1', label: 'Address — Line 1', type: 'text', defaultValue: 'BIMC Hospital Nusa Dua',
      admin: { description: 'Line 1 of the clinic address. Shown on /contact in the Visit section and in the footer brand column. e.g. venue name.' } },
    { name: 'addressLine2', label: 'Address — Line 2', type: 'text', defaultValue: 'Kawasan ITDC Blok D',
      admin: { description: 'Line 2 of the clinic address (street / suburb).' } },
    { name: 'city', label: 'City', type: 'text', defaultValue: 'Nusa Dua',
      admin: { description: 'City. Rendered on the same line as postalCode, e.g. "Nusa Dua 80363".' } },
    { name: 'postalCode', type: 'text', defaultValue: '80363',
      admin: { description: 'Postal code. Rendered alongside city.', hidden: true } },
    { name: 'country', type: 'text', defaultValue: 'Bali, Indonesia',
      admin: { description: 'Last line of the address (region + country, or just country).', hidden: true } },
    { name: 'hoursMonFri', label: 'Hours — Mon–Fri', type: 'text', defaultValue: 'Mon–Fri · 09:00–17:00',
      admin: { description: 'Primary clinic-hours line shown on /contact ("Hours · Clinic" block, line 1).' } },
    { name: 'hoursSatSun', label: 'Hours — Saturday', type: 'text', defaultValue: 'Sat · By appointment',
      admin: { description: 'Secondary clinic-hours line shown on /contact ("Hours · Clinic" block, line 2).' } },
    { name: 'googleMapsUrl', label: 'Google Maps URL', type: 'text',
      admin: { description: 'Google Maps URL. Powers the "Open in Maps" + "Get directions" buttons in the /contact Visit section. Leave blank to hide both buttons.' } },
    {
      name: 'socialLinks',
      type: 'array',
      admin: { description: 'Social links shown in the footer "Connect" column. Order here = display order.' },
      fields: [
        { name: 'platform', type: 'select', required: true, options: [
          { label: 'Instagram', value: 'instagram' },
          { label: 'Facebook', value: 'facebook' },
          { label: 'WhatsApp', value: 'whatsapp' },
          { label: 'TikTok', value: 'tiktok' },
          { label: 'YouTube', value: 'youtube' },
          { label: 'LinkedIn', value: 'linkedin' },
          { label: 'X / Twitter', value: 'x' },
        ] },
        { name: 'url', type: 'text', required: true },
      ],
    },
    { name: 'defaultLocale', type: 'select', defaultValue: 'en',
      admin: { description: 'Default site locale. Currently EN — Phase 9 will add ID and activate the EN|ID switcher.', hidden: true },
      options: [{ label: 'English', value: 'en' }, { label: 'Bahasa Indonesia', value: 'id' }] },
    // currencyDisplayMode removed 25.17 — was dead code; PriceTag switches on
    // locale (EN = IDR + AUD, ID = IDR only). The selector below was never
    // read by any consumer.
    { name: 'defaultOgImage', type: 'upload', relationTo: 'media',
      admin: { description: 'Fallback Open Graph image for social-share previews when a page record has no OG image of its own.', hidden: true } },
    { name: 'defaultMetaDescription', type: 'textarea', localized: true,
      admin: { description: 'Fallback SEO description used when a page record has no description of its own.', hidden: true } },
  ],
}
