import type { GlobalConfig } from 'payload'
import { isAuthenticated, readPublic } from '../lib/access'
import { revalidateGlobalAfterChange } from '../lib/revalidate'
import { apiWarningField } from '../lib/api-warning'

export const Settings: GlobalConfig = {
  slug: 'settings',
  admin: {
    group: 'Homepage',
    description: 'Site-wide identity used on every page: name, address, contact details, WhatsApp number, currency rules, social links. Anything that appears in the footer, the contact page, or feeds the floating chrome.',
  },
  access: { read: readPublic, update: isAuthenticated },
  hooks: revalidateGlobalAfterChange(),
  fields: [
    apiWarningField,
    { name: 'siteName', type: 'text', defaultValue: 'BIMC CosMedic',
      admin: { description: 'Used in <title> tags, OG meta, footer copyright, header logo alt-text. Visible on every page.' } },
    { name: 'siteTagline', type: 'text',
      admin: { description: 'Short tagline used in SEO meta + share previews. Not currently rendered on-screen.' } },
    { name: 'defaultOgImage', type: 'upload', relationTo: 'media',
      admin: { description: 'Fallback Open Graph image for social-share previews when a page record has no OG image of its own.' } },
    { name: 'defaultMetaDescription', type: 'textarea',
      admin: { description: 'Fallback SEO description used when a page record has no description of its own.' } },
    { name: 'audToIdrRate', type: 'number', defaultValue: 10500,
      admin: { description: 'AUD → IDR conversion rate used to derive IDR display values on /pricing and procedure cards when only one currency is entered. Per brand.pdf May 2026 = 10,500.' } },
    { name: 'roundIdrTo', type: 'number', defaultValue: 50000,
      admin: { description: 'Round computed IDR to nearest N when converting from AUD. Default 50,000.' } },
    { name: 'contactEmail', type: 'text', defaultValue: 'cosmedic@bimcbali.com',
      admin: { description: 'Shown on /contact and in footer "Connect" column.' } },
    { name: 'contactPhone', type: 'text',
      admin: { description: 'Shown on /contact and in footer.' } },
    { name: 'whatsappNumber', type: 'text', defaultValue: '+62-XXX-XXXX-XXXX',
      admin: { description: 'Drives the floating green WhatsApp bubble bottom-right of every page AND the WhatsApp link in the footer "Connect" column. Format: E.164 (+countrycode-number).' } },
    { name: 'addressLine1', type: 'text', defaultValue: 'Kawasan BTDC Blok D',
      admin: { description: 'First line of the address in the footer brand column.' } },
    { name: 'addressLine2', type: 'text', defaultValue: 'Nusa Dua',
      admin: { description: 'Second line of the address in the footer brand column.' } },
    { name: 'city', type: 'text', defaultValue: 'Bali',
      admin: { description: 'City line in the footer brand column.' } },
    { name: 'postalCode', type: 'text', defaultValue: '80363',
      admin: { description: 'Postal code in the footer brand column.' } },
    { name: 'country', type: 'text', defaultValue: 'Indonesia',
      admin: { description: 'Country in the footer brand column.' } },
    { name: 'hoursMonFri', type: 'text', defaultValue: 'Mon–Fri · 09:00–17:00',
      admin: { description: 'Opening hours shown on /contact.' } },
    { name: 'hoursSatSun', type: 'text', defaultValue: 'Sat · By appointment',
      admin: { description: 'Weekend hours shown on /contact.' } },
    { name: 'googleMapsUrl', type: 'text',
      admin: { description: 'Powers the "Get directions" link / embedded map on /contact.' } },
    {
      name: 'socialLinks',
      type: 'array',
      admin: { description: 'Social links shown in the footer "Connect" column. Order here = display order.' },
      fields: [
        { name: 'platform', type: 'select', required: true, options: [
          { label: 'Instagram', value: 'instagram' },
          { label: 'Facebook', value: 'facebook' },
          { label: 'WhatsApp', value: 'whatsapp' },
          { label: 'TikTok', value: 'tiktok' },
          { label: 'YouTube', value: 'youtube' },
          { label: 'LinkedIn', value: 'linkedin' },
          { label: 'X / Twitter', value: 'x' },
        ] },
        { name: 'url', type: 'text', required: true },
      ],
    },
    { name: 'defaultLocale', type: 'select', defaultValue: 'en',
      admin: { description: 'Default site locale. Currently EN — Phase 9 will add ID and activate the EN|ID switcher.' },
      options: [{ label: 'English', value: 'en' }, { label: 'Bahasa Indonesia', value: 'id' }] },
    { name: 'currencyDisplayMode', type: 'select', defaultValue: 'idr-with-aud',
      admin: { description: 'How prices render across the whole site: IDR-only, or IDR primary + AUD italic.' },
      options: [
        { label: 'IDR only', value: 'idr-only' },
        { label: 'IDR primary + AUD italic', value: 'idr-with-aud' },
      ] },
  ],
}
