import type { GlobalConfig } from 'payload'
import { isAuthenticated, readPublic } from '../lib/access'
import { revalidateGlobalAfterChange } from '../lib/revalidate'
import { apiWarningField } from '../lib/api-warning'

export const Settings: GlobalConfig = {
  slug: 'settings',
  label: 'l. Settings',
  admin: {
    group: 'a. Homepage',
    description: 'Site-wide identity used on every page: name, address, contact details, WhatsApp number, currency rules, social links. Anything that appears in the footer, the contact page, or feeds the floating chrome.',
  },
  access: { read: readPublic, update: isAuthenticated },
  hooks: revalidateGlobalAfterChange(),
  fields: [
    apiWarningField,
    { name: 'siteName', type: 'text', defaultValue: 'BIMC CosMedic',
      admin: { description: 'Used in <title> tags, OG meta, footer copyright, header logo alt-text. Visible on every page.' } },
    { name: 'siteTagline', type: 'text',
      admin: { description: 'Short tagline used in SEO meta + share previews. Not currently rendered on-screen.' } },
    { name: 'defaultOgImage', type: 'upload', relationTo: 'media',
      admin: { description: 'Fallback Open Graph image for social-share previews when a page record has no OG image of its own.' } },
    { name: 'defaultMetaDescription', type: 'textarea',
      admin: { description: 'Fallback SEO description used when a page record has no description of its own.' } },
    { name: 'audToIdrRate', type: 'number', defaultValue: 10500,
      admin: { description: 'AUD → IDR conversion rate used to derive IDR display values on /pricing and procedure cards when only one currency is entered. Per brand.pdf May 2026 = 10,500.' } },
    { name: 'roundIdrTo', type: 'number', defaultValue: 50000,
      admin: { description: 'Round computed IDR to nearest N when converting from AUD. Default 50,000.' } },
    { name: 'contactEmail', type: 'text', defaultValue: 'cosmedic@bimcbali.com',
      admin: { description: 'General clinic email. Shown on /contact under "Direct lines · Email" AND in the footer "Connect" column.' } },
    { name: 'pressEmail', type: 'text', defaultValue: 'press@bimccosmedic.com',
      admin: { description: 'Press / media email. Shown on /contact under "Direct lines · Press". Edit once here.' } },
    { name: 'contactPhone', type: 'text',
      admin: { description: 'Concierge phone (E.164 formatted). Shown on /contact under "Direct lines · Concierge".' } },
    { name: 'whatsappNumber', type: 'text', defaultValue: '+62-XXX-XXXX-XXXX',
      admin: { description: 'Concierge WhatsApp number. Single source for: the floating green WhatsApp bubble on every page (wa.me link built from the digits), the footer "Connect" column WhatsApp link, AND the /contact "Direct lines · WhatsApp" displayed value. Format: E.164 (+countrycode-number) — the digits are extracted for wa.me; the formatted string is what readers see.' } },
    { name: 'addressLine1', type: 'text', defaultValue: 'BIMC Hospital Nusa Dua',
      admin: { description: 'Line 1 of the clinic address. Shown on /contact in the Visit section and in the footer brand column. e.g. venue name.' } },
    { name: 'addressLine2', type: 'text', defaultValue: 'Kawasan ITDC Blok D',
      admin: { description: 'Line 2 of the clinic address (street / suburb).' } },
    { name: 'city', type: 'text', defaultValue: 'Nusa Dua',
      admin: { description: 'City. Rendered on the same line as postalCode, e.g. "Nusa Dua 80363".' } },
    { name: 'postalCode', type: 'text', defaultValue: '80363',
      admin: { description: 'Postal code. Rendered alongside city.' } },
    { name: 'country', type: 'text', defaultValue: 'Bali, Indonesia',
      admin: { description: 'Last line of the address (region + country, or just country).' } },
    { name: 'hoursMonFri', type: 'text', defaultValue: 'Mon–Fri · 09:00–17:00',
      admin: { description: 'Primary clinic-hours line shown on /contact ("Hours · Clinic" block, line 1).' } },
    { name: 'hoursSatSun', type: 'text', defaultValue: 'Sat · By appointment',
      admin: { description: 'Secondary clinic-hours line shown on /contact ("Hours · Clinic" block, line 2).' } },
    { name: 'googleMapsUrl', type: 'text',
      admin: { description: 'Google Maps URL. Powers the "Open in Maps" + "Get directions" buttons in the /contact Visit section. Leave blank to hide both buttons.' } },
    {
      name: 'socialLinks',
      type: 'array',
      admin: { description: 'Social links shown in the footer "Connect" column. Order here = display order.' },
      fields: [
        { name: 'platform', type: 'select', required: true, options: [
          { label: 'Instagram', value: 'instagram' },
          { label: 'Facebook', value: 'facebook' },
          { label: 'WhatsApp', value: 'whatsapp' },
          { label: 'TikTok', value: 'tiktok' },
          { label: 'YouTube', value: 'youtube' },
          { label: 'LinkedIn', value: 'linkedin' },
          { label: 'X / Twitter', value: 'x' },
        ] },
        { name: 'url', type: 'text', required: true },
      ],
    },
    { name: 'defaultLocale', type: 'select', defaultValue: 'en',
      admin: { description: 'Default site locale. Currently EN — Phase 9 will add ID and activate the EN|ID switcher.' },
      options: [{ label: 'English', value: 'en' }, { label: 'Bahasa Indonesia', value: 'id' }] },
    { name: 'currencyDisplayMode', type: 'select', defaultValue: 'idr-with-aud',
      admin: { description: 'How prices render across the whole site: IDR-only, or IDR primary + AUD italic.' },
      options: [
        { label: 'IDR only', value: 'idr-only' },
        { label: 'IDR primary + AUD italic', value: 'idr-with-aud' },
      ] },
  ],
}
