--
-- PostgreSQL database dump
--

\restrict KSI8Pf2pmeiJeN1uisJ3nUHZ0zU2B3u56wKI7yohfGUgqmgtpD7AVd4yfDFtKNd

-- Dumped from database version 18.4 (Ubuntu 18.4-1.pgdg24.04+1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: sub_categories; Type: TABLE DATA; Schema: public; Owner: cosmedic
--

COPY public.sub_categories (id, slug, parent_id, title, chapter_title_a, chapter_title_b, tagline, lede, intro, overview, lead_surgeon_id, hero_image_id, seo_title, seo_description, seo_og_image_id, seo_canonical, seo_noindex, sort_order, updated_at, created_at) FROM stdin;
2	surgical-body	1	Body	Body,	in proportion.	Contouring with the same restraint as our facial work.	Liposculpture, abdominoplasty, and post-pregnancy or post-weight-loss restoration — performed under our highest safety thresholds, with surgeon-supervised recovery.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Body work is rewarding when it suits your anatomy and your life — and ill-advised when it doesn't. We will quote you for what we believe is safe and sensible, sometimes less than you came in expecting. Our consultations include a frank conversation about non-surgical alternatives where they might serve you better.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	1	\N	\N	\N	\N	\N	f	1	2026-05-20 12:55:41.863+00	2026-05-20 12:54:44.43+00
4	breast-recon	2	Breast Reconstruction	Breast	reconstruction.	Restoration after mastectomy, with proportion and symmetry in mind.	Implant-based and autologous (DIEP, TRAM) breast reconstruction after mastectomy — performed by ISAPS-credentialed reconstructive surgeons, often in coordination with oncology teams in your home country.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Our reconstructive practice is a small subset of our overall surgical volume — by design. We perform DIEP, TRAM, and implant-based reconstructions; we coordinate with international oncologists via your concierge; and we provide full surgical documentation for insurance claims, which often cover reconstruction in part or whole.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	4	\N	\N	\N	\N	\N	f	3	2026-05-20 12:55:41.999+00	2026-05-20 12:54:44.59+00
7	injectables	3	Injectables	Quiet hands,	small refinements.	Less product, less heat, less everything you might expect.	Botulinum toxin, dermal fillers, bio-remodelling and skin-quality injectables — performed by medical injectors, never technicians, with a deliberately conservative protocol.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "We work to a single principle: that the best injectable work is the kind that nobody sees. Health Canada and TGA-approved products only; medical injectors only; private treatment rooms only. We never run promotional pricing on injectables, because it changes the conversation in a way we are not comfortable with.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	5	\N	\N	\N	\N	\N	f	6	2026-05-20 12:55:42.198+00	2026-05-20 12:54:44.764+00
11	hair-therapy	4	Follicle Therapy	Strengthening,	before surgery.	Therapy first; surgery only when therapy can't.	PRP, polynucleotides, and topical protocols — for patients with active follicles that are weakening, where transplant would be premature.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Therapy is best suited to patients whose follicles are still active but weakening. We assess miniaturisation, donor density, and your timeline; then design a programme that gives therapy a fair trial before considering surgery.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	1	\N	\N	\N	\N	\N	f	10	2026-05-20 12:55:42.521+00	2026-05-20 12:54:44.972+00
13	alignment	5	Alignment	Aligned,	quietly.	Clear aligners and lingual alternatives, planned around your travel.	Clear alignment and discrete orthodontic options for adults — scanned, planned, and started during a single Bali visit, then maintained remotely.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "We use Invisalign, ClearCorrect, and a Korean-Japanese lingual system for cases where aligners aren't suitable. Treatment ranges from six to eighteen months depending on complexity. Remote reviews quarterly; in-person review when convenient.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	2	\N	\N	\N	\N	\N	f	12	2026-05-20 12:55:42.653+00	2026-05-20 12:54:45.126+00
14	whitening	5	Whitening	Brighter,	without overdoing it.	Professional whitening protocols — for natural-looking results, not Hollywood ones.	In-chair professional whitening, take-home protocols, and combined approaches — calibrated for natural-looking brightness rather than aggressive shade changes.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "We use Zoom and Opalescence — two of the most respected professional protocols. In-chair sessions deliver immediate change; take-home trays deliver more durable change over two weeks. The combined approach is most patients' best option.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	2	\N	\N	\N	\N	\N	f	13	2026-05-20 12:55:42.719+00	2026-05-20 12:54:45.17+00
1	surgical-face	1	Face	The face,	refined.	Quiet work for the most considered part of the body.	Rhinoplasty, facelift, eyelid surgery, and the subtler refinements — performed in our ACHSI-accredited theatres with a structure-preserving, conservative approach.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "We approach facial surgery as long-term investment in your face, not a single intervention. A well-judged rhinoplasty looks better at year five than year one. A deep-plane facelift outlasts a SMAS by a decade. We prefer the operation that earns its keep over time — and we will tell you when surgery is the wrong answer.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	1	\N	\N	\N	\N	\N	f	0	2026-05-20 12:55:41.793+00	2026-05-20 12:54:44.353+00
10	hair-fue	4	FUE Surgical	Returning,	quietly.	Single-follicle transplantation, designed to never be detected.	Sapphire FUE and DHI implantation — for hair restoration that respects what your face has always done, and that the world will never identify as transplanted.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "We perform between two and four FUE cases per day, capped deliberately. Each case has one dedicated lead surgeon and a team of three certified technicians. Single follicles in the hairline, two- and three-hair units behind. Single-day or staged depending on graft count.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	1	\N	\N	\N	\N	\N	f	9	2026-05-20 12:55:42.432+00	2026-05-20 12:54:44.917+00
3	breast	1	Breast	Considered,	your own.	Conservative work, proportioned to your anatomy.	A complete repertoire of breast surgery — implant-based augmentation, lifting, reduction, and refinement — performed in our ACHSI-accredited theatres by ISAPS-member plastic surgeons. We size for proportion and longevity, not volume.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Breast surgery, in our view, is anatomical work first and aesthetic work second. We size implants in millilitres rather than cup sizes, plan incisions around lifestyle and lactation goals, and prefer the smaller intervention every time we can defend it. Recovery is supervised — daily nursing visits in a private villa, two scheduled surgeon reviews, and twelve months of telehealth follow-up after you fly home.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	1	\N	\N	\N	\N	\N	f	2	2026-05-20 12:55:41.933+00	2026-05-20 12:54:44.523+00
8	laser	3	Laser & Resurfacing	Light,	with restraint.	Gold-standard platforms, dialled to the minimum effective dose.	Fractional laser, IPL, chemical peels, and RF microneedling — used precisely, scheduled around your visit, and always with conservative settings.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Our laser suite uses Lumenis, Sciton, and Sylfirm — three of the most respected platforms in the world for fractional, IPL, and RF microneedling respectively. Settings are tailored per session, per skin type, and per season. Aggressive single-session treatments are not how we practice.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	5	\N	\N	\N	\N	\N	f	7	2026-05-20 12:55:42.263+00	2026-05-20 12:54:44.821+00
9	skin	3	Skin Health	Skin,	considered.	Medical facials and structured skin protocols.	Medical-grade facials, peels, and structured at-home skin protocols — designed for skin that needs more than maintenance but less than intervention.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Our medical facials use cosmeceutical-grade product (SkinCeuticals, ZO Skin Health, Obagi) and are delivered by trained skin therapists working alongside the medical team. Every protocol begins with skin diagnosis, ends with a take-home plan, and includes review at six weeks.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	5	\N	\N	\N	\N	\N	f	8	2026-05-20 12:55:42.338+00	2026-05-20 12:54:44.877+00
6	craniofacial	2	Craniofacial	Craniofacial &	reconstructive.	Complex facial reconstruction by craniomaxillofacial subspecialists.	Cleft lip and palate, maxillofacial trauma, orbital reconstruction, and microtia ear reconstruction — performed by our craniomaxillofacial-credentialed surgeon with international fellowship training.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "We treat congenital craniofacial conditions, post-traumatic deformities, and complex acquired conditions of the face, skull, and jaw. Many of our craniofacial patients are referred through international charity and aid networks; we maintain a small pro-bono pathway alongside our private practice.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	4	\N	\N	\N	\N	\N	f	5	2026-05-20 12:55:42.134+00	2026-05-20 12:54:44.709+00
5	trauma	2	Trauma & Scar	Trauma &	scar repair.	Reconstruction after injury, burn, or unsatisfactory prior surgery.	Scar revision, burn reconstruction, skin grafts, and complex flap repair — for patients seeking refinement after trauma, surgery, or burn injury.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Our reconstructive team includes a fellowship-trained burn and trauma reconstructive surgeon. We offer everything from minor scar revision under local anaesthetic to complex multi-stage flap reconstruction. We will not promise scar erasure — no surgeon honestly can — but we can almost always improve.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	3	\N	\N	\N	\N	\N	f	4	2026-05-20 12:55:42.055+00	2026-05-20 12:54:44.663+00
12	veneers	5	Veneers	The smile,	rebuilt.	Porcelain or composite, paced to suit your visit.	Porcelain veneers, composite veneers, and complete smile makeovers — designed in collaboration with our on-staff ceramicist over three visits and fourteen days.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Our dental studio is small — two surgeries, one ceramicist on staff, conservative practice. We prefer minimal-prep veneers where the case allows, and we always include a try-in stage so you can see and feel the result before final placement.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	2	\N	\N	\N	\N	\N	f	11	2026-05-20 12:55:42.581+00	2026-05-20 12:54:45.057+00
17	bariatric	6	Bariatric Surgery	Bariatric	surgery.	Laparoscopic surgical pathways for serious weight loss.	Sleeve gastrectomy, gastric bypass, and revision bariatric surgery — performed laparoscopically by our consultant bariatric surgeon in our ACHSI-accredited theatres, with structured multidisciplinary support before and after.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Performed by a consultant bariatric surgeon with international fellowship training and over 1,500 cases. All procedures are laparoscopic (keyhole) with same-day mobilisation. We are conservative about combining bariatric surgery with body-contouring work — the latter is best deferred until weight has been stable for twelve months.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	1	\N	\N	\N	\N	\N	f	16	2026-05-20 12:55:43.069+00	2026-05-20 12:54:45.337+00
16	endoscopic	6	Endoscopic	Endoscopic	weight loss.	Non-incisional procedures performed through the mouth, no scars.	Intragastric balloons and endoscopic sleeve gastroplasty (ESG) — performed under sedation through the mouth, with no incisions and same-week recovery.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Endoscopic procedures are performed by our consultant gastroenterologist, with full bariatric multidisciplinary support: dietitian, behavioural health, and exercise physiology. Recovery is days, not weeks; outcomes are weeks, not minutes.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	1	\N	\N	\N	\N	\N	f	15	2026-05-20 12:55:42.904+00	2026-05-20 12:54:45.294+00
15	glp-1	6	Medical	Medical weight	loss.	Pharmacological pathways, supported by nutrition and behaviour.	GLP-1 medications, structured dietitian programmes, and prescription protocols — for patients seeking sustained weight loss without surgery, with monthly monitoring and lifestyle support.	\N	{"root": {"type": "root", "format": "", "indent": 0, "version": 1, "children": [{"type": "paragraph", "format": "", "indent": 0, "version": 1, "children": [{"mode": "normal", "text": "Our medical pathway is led by a consultant endocrinologist working alongside our dietitian and behavioural-health team. We prescribe TGA- and FDA-approved medications only, monitor monthly, and step down or transition to maintenance once your target is reached. We will not prescribe without ongoing supervision.", "type": "text", "style": "", "detail": 0, "format": 0, "version": 1}], "direction": "ltr", "textFormat": 0}], "direction": "ltr"}}	5	\N	\N	\N	\N	\N	f	14	2026-05-20 12:55:42.803+00	2026-05-20 12:54:45.222+00
\.


--
-- Name: sub_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cosmedic
--

SELECT pg_catalog.setval('public.sub_categories_id_seq', 17, true);


--
-- PostgreSQL database dump complete
--

\unrestrict KSI8Pf2pmeiJeN1uisJ3nUHZ0zU2B3u56wKI7yohfGUgqmgtpD7AVd4yfDFtKNd

